packages:
  - "apps/*"
  - "packages/*"
  - "contracts"

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false

onlyBuiltDependencies:
  - "@reown/appkit"
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "unrs-resolver"
